"""Tests for curation scoring."""
from __future__ import annotations

import pytest

from brandmint.publishing.curation_scorer import (
    CurationScore,
    CurationWeights,
    calculate_base_score,
    calculate_placeholder_penalty,
    calculate_meta_penalty,
    calculate_curation_score,
    calculate_curation_scores,
    filter_uploadable_documents,
    generate_curation_report,
    get_weights_for_profile,
)


class TestCalculateBaseScore:
    """Test base score calculation."""

    def test_high_score_for_clean_long_content(self):
        text = "We believe in creating exceptional products that deliver value to our customers every single day. Our mission is to transform the industry through innovative solutions and customer-centric design. We have built a comprehensive platform that addresses all key market needs and provides outstanding user experience."
        score = calculate_base_score(text)
        assert score > 50

    def test_low_score_for_short_content(self):
        text = "Short."
        score = calculate_base_score(text)
        assert score < 50

    def test_penalty_for_placeholders(self):
        clean_text = "We believe in creating exceptional products that deliver value to our customers every single day. Our mission is to transform the industry through innovative solutions."
        placeholder_text = "TODO TBD FIXME XXX HACK TODO TBD FIXME XXX HACK TODO " * 3
        clean_score = calculate_base_score(clean_text)
        placeholder_score = calculate_base_score(placeholder_text)
        assert placeholder_score < clean_score

    def test_score_bounds(self):
        text = "Test content."
        score = calculate_base_score(text)
        assert 0.0 <= score <= 100.0


class TestCalculatePlaceholderPenalty:
    """Test placeholder penalty calculation."""

    def test_zero_penalty_for_clean_text(self):
        text = "Clean content without any placeholders or markers and sufficient length to avoid short content detection patterns that might trigger false positives in the placeholder detection system."
        penalty = calculate_placeholder_penalty(text)
        assert penalty == 0.0

    def test_high_penalty_for_placeholder_heavy_text(self):
        text = "{{name}} {{company}} {{product}} {{feature}} {{benefit}} " * 5
        penalty = calculate_placeholder_penalty(text)
        assert penalty > 0

    def test_penalty_scales_with_density(self):
        light_text = "Some content with one TODO marker and additional text to ensure we exceed the minimum length threshold for proper scoring."
        heavy_text = "TODO TBD FIXME XXX HACK TODO TBD FIXME XXX HACK TODO " * 3
        light_penalty = calculate_placeholder_penalty(light_text)
        heavy_penalty = calculate_placeholder_penalty(heavy_text)
        # Light text may have some penalty but heavy should be higher
        assert heavy_penalty >= light_penalty


class TestCalculateMetaPenalty:
    """Test meta-content penalty calculation."""

    def test_zero_penalty_for_brand_native_text(self):
        text = "We believe in creating exceptional products that deliver value."
        penalty = calculate_meta_penalty(text)
        assert penalty == 0.0

    def test_penalty_for_ai_references(self):
        text = "This content was generated by AI using GPT-4 and Claude."
        penalty = calculate_meta_penalty(text)
        assert penalty > 0

    def test_penalty_scales_with_meta_density(self):
        light_text = "We believe in quality. This was generated by AI."
        heavy_text = "Generated by AI using GPT. Created by Claude model. This document was produced by the system using AI language model technology."
        light_penalty = calculate_meta_penalty(light_text)
        heavy_penalty = calculate_meta_penalty(heavy_text)
        assert heavy_penalty > light_penalty


class TestCalculateCurationScore:
    """Test final curation score calculation."""

    def test_uploadable_for_high_quality_content(self):
        text = "We believe in creating exceptional products that deliver value to our customers every single day. Our mission is to transform the industry through innovative solutions and customer-centric design. We have built a comprehensive platform that addresses all key market needs and provides outstanding user experience. Our team has worked tirelessly to ensure that every detail is perfect and that our customers receive the best possible service. This comprehensive approach ensures quality."
        score = calculate_curation_score("doc1", text)
        assert score.is_uploadable
        assert score.final_score >= 70

    def test_not_uploadable_for_placeholder_heavy_content(self):
        text = "TODO TBD FIXME XXX HACK TODO TBD FIXME XXX HACK TODO " * 5
        score = calculate_curation_score("doc1", text)
        assert not score.is_uploadable
        assert score.suppression_reasons

    def test_not_uploadable_for_meta_heavy_content(self):
        text = "Generated by AI using GPT. Created by Claude model. This document was produced by the system using AI language model technology. " * 3
        score = calculate_curation_score("doc1", text)
        assert not score.is_uploadable

    def test_score_components(self):
        text = "We believe in quality. TODO: fix this later. " * 5
        score = calculate_curation_score("doc1", text)
        assert score.base_score >= 0
        assert score.placeholder_penalty >= 0
        assert score.meta_penalty >= 0
        assert 0 <= score.final_score <= 100

    def test_custom_weights(self):
        text = "Some content with moderate quality and length."
        weights = CurationWeights(min_uploadable_score=90.0)
        score = calculate_curation_score("doc1", text, weights=weights)
        assert not score.is_uploadable  # High threshold


class TestCalculateCurationScores:
    """Test batch score calculation."""

    def test_scores_multiple_documents(self):
        docs = {
            "doc1": "High quality content with sufficient length and no placeholders or issues.",
            "doc2": "TODO: Incomplete content.",
        }
        scores = calculate_curation_scores(docs)
        assert len(scores) == 2
        assert "doc1" in scores
        assert "doc2" in scores

    def test_empty_documents_dict(self):
        scores = calculate_curation_scores({})
        assert scores == {}


class TestFilterUploadableDocuments:
    """Test document filtering by uploadability."""

    def test_filters_non_uploadable(self):
        docs = {
            "doc1": "High quality content with sufficient length and no placeholders or issues. This document contains comprehensive information that meets all quality standards and should be considered uploadable. The content is well-written and provides value to readers.",
            "doc2": "TODO: Incomplete.",
        }
        weights = CurationWeights(min_uploadable_score=60.0)
        scores = calculate_curation_scores(docs, weights=weights)
        filtered = filter_uploadable_documents(docs, scores)
        # doc1 should be uploadable with adjusted threshold
        assert "doc1" in filtered

    def test_empty_documents(self):
        filtered = filter_uploadable_documents({}, {})
        assert filtered == {}


class TestGenerateCurationReport:
    """Test report generation."""

    def test_generates_report_with_suppressed_docs(self):
        scores = {
            "doc1": CurationScore(doc_id="doc1", base_score=80, placeholder_penalty=5, meta_penalty=0, final_score=75, is_uploadable=True),
            "doc2": CurationScore(
                doc_id="doc2",
                base_score=30,
                placeholder_penalty=40,
                meta_penalty=20,
                final_score=20,
                is_uploadable=False,
                suppression_reasons=["Score too low"],
            ),
        }
        report = generate_curation_report(scores)
        assert "# Curation Scoring Report" in report
        assert "Total documents: 2" in report
        assert "Uploadable: 1" in report
        assert "Suppressed: 1" in report
        assert "## Suppressed Documents" in report
        assert "### doc2" in report

    def test_generates_report_with_no_suppressed_docs(self):
        scores = {
            "doc1": CurationScore(doc_id="doc1", base_score=80, placeholder_penalty=5, meta_penalty=0, final_score=75, is_uploadable=True),
        }
        report = generate_curation_report(scores)
        assert "# Curation Scoring Report" in report
        assert "Suppressed: 0" in report
        assert "## Suppressed Documents" not in report


class TestGetWeightsForProfile:
    """Test weight presets for profiles."""

    def test_brand_public_weights(self):
        weights = get_weights_for_profile("brand-public")
        assert weights.min_uploadable_score == 75.0
        assert weights.placeholder_penalty_multiplier == 2.0

    def test_strategy_internal_weights(self):
        weights = get_weights_for_profile("strategy-internal")
        assert weights.min_uploadable_score == 60.0
        assert weights.placeholder_penalty_multiplier == 1.5

    def test_kickstarter_conditional_weights(self):
        weights = get_weights_for_profile("kickstarter-conditional")
        assert weights.min_uploadable_score == 85.0
        assert weights.placeholder_penalty_multiplier == 3.0

    def test_debug_internal_weights(self):
        weights = get_weights_for_profile("debug-internal")
        assert weights.min_uploadable_score == 0.0
        assert weights.placeholder_penalty_multiplier == 0.5

    def test_unknown_profile_defaults_to_brand_public(self):
        weights = get_weights_for_profile("unknown")
        brand_public_weights = get_weights_for_profile("brand-public")
        assert weights.min_uploadable_score == brand_public_weights.min_uploadable_score
