"""Tests for anti-meta transform pipeline."""
from __future__ import annotations

import pytest

from brandmint.publishing.anti_meta_transform import (
    AntiMetaPolicy,
    MetaDetection,
    TransformResult,
    detect_meta_content,
    apply_anti_meta_transform,
    transform_document,
    transform_documents,
    generate_diff_report,
    get_policy_for_profile,
)


class TestDetectMetaContent:
    """Test meta-content detection."""

    def test_detects_ai_reference(self):
        text = "This content was generated by AI using GPT-4."
        detections = detect_meta_content(text)
        assert any(d.pattern_name == "ai_reference" for d in detections)

    def test_detects_generation_process(self):
        text = "The document was created using the brandmint pipeline."
        detections = detect_meta_content(text)
        assert any(d.pattern_name == "generation_process" for d in detections)

    def test_detects_model_reference(self):
        text = "The model output shows strong brand alignment."
        detections = detect_meta_content(text)
        assert any(d.pattern_name == "model_reference" for d in detections)

    def test_detects_disclaimer(self):
        text = "Note: This content was generated by AI and should be reviewed."
        detections = detect_meta_content(text)
        assert any(d.pattern_name == "disclaimer" for d in detections)

    def test_no_detections_for_brand_native_text(self):
        text = "We believe in creating exceptional products that deliver value to our customers."
        detections = detect_meta_content(text)
        # Should not detect brand-native content as meta
        assert len(detections) == 0

    def test_respects_enabled_patterns(self):
        text = "This content was generated by AI."
        policy = AntiMetaPolicy(enabled_patterns={"ai_reference"})
        detections = detect_meta_content(text, policy)
        # Should only detect ai_reference, not generation_process
        assert all(d.pattern_name == "ai_reference" for d in detections)

    def test_respects_min_confidence(self):
        text = "The system produces results."
        policy = AntiMetaPolicy(min_confidence=0.9)
        detections = detect_meta_content(text, policy)
        # Low confidence matches should be filtered
        assert all(d.confidence >= 0.9 for d in detections)


class TestApplyAntiMetaTransform:
    """Test anti-meta transform application."""

    def test_transform_removes_meta_content(self):
        text = "This document was generated by AI using GPT-4. We believe in quality."
        result = apply_anti_meta_transform(text)
        assert result.changes_made > 0
        assert "AI" not in result.transformed_text or "AI" in result.transformed_text.lower()

    def test_transform_preserves_brand_voice(self):
        text = "We believe in creating exceptional products. This was generated by AI."
        result = apply_anti_meta_transform(text)
        assert result.style_preserved
        assert "we believe" in result.transformed_text.lower()

    def test_transform_returns_original_when_no_meta(self):
        text = "We deliver exceptional value to our customers every day."
        result = apply_anti_meta_transform(text)
        assert result.changes_made == 0
        assert result.transformed_text == text

    def test_transform_calculates_confidence(self):
        text = "Generated by AI model."
        result = apply_anti_meta_transform(text)
        assert 0.0 <= result.confidence_score <= 1.0

    def test_transform_cleans_up_spacing(self):
        text = "This  was   generated by    AI."
        result = apply_anti_meta_transform(text)
        # Should not have multiple consecutive spaces
        assert "  " not in result.transformed_text


class TestTransformDocuments:
    """Test batch document transformation."""

    def test_transforms_multiple_documents(self):
        docs = {
            "doc1": "Generated by AI.",
            "doc2": "We believe in quality.",
            "doc3": "This content was created using the pipeline.",
        }
        results = transform_documents(docs)
        assert len(results) == 3
        assert all(isinstance(r, TransformResult) for r in results.values())

    def test_empty_documents_dict(self):
        results = transform_documents({})
        assert results == {}


class TestGenerateDiffReport:
    """Test diff report generation."""

    def test_generates_report_with_changes(self):
        results = {
            "doc1": TransformResult(
                original_text="Generated by AI.",
                transformed_text="",
                detections=[MetaDetection(
                    pattern_name="ai_reference",
                    match_text="Generated by AI",
                    start_pos=0,
                    end_pos=15,
                    confidence=0.9,
                )],
                changes_made=1,
                confidence_score=0.9,
                style_preserved=True,
            ),
            "doc2": TransformResult(
                original_text="We believe in quality.",
                transformed_text="We believe in quality.",
                detections=[],
                changes_made=0,
                confidence_score=1.0,
                style_preserved=True,
            ),
        }
        report = generate_diff_report(results)
        assert "# Anti-Meta Transform Report" in report
        assert "## doc1" in report
        assert "## doc2" not in report  # No changes, should not appear
        assert "Total documents: 2" in report
        assert "Documents with changes: 1" in report

    def test_generates_empty_report_when_no_changes(self):
        results = {
            "doc1": TransformResult(
                original_text="Clean text.",
                transformed_text="Clean text.",
                detections=[],
                changes_made=0,
                confidence_score=1.0,
                style_preserved=True,
            ),
        }
        report = generate_diff_report(results)
        assert "# Anti-Meta Transform Report" in report
        assert "Total documents: 1" in report
        assert "Documents with changes: 0" in report


class TestGetPolicyForProfile:
    """Test policy presets for profiles."""

    def test_brand_public_policy(self):
        policy = get_policy_for_profile("brand-public")
        assert policy.allow_partial_meta is False
        assert policy.max_meta_percentage == 5.0
        assert len(policy.enabled_patterns) == 8

    def test_strategy_internal_policy(self):
        policy = get_policy_for_profile("strategy-internal")
        assert policy.allow_partial_meta is True
        assert policy.max_meta_percentage == 15.0
        assert "ai_reference" in policy.enabled_patterns

    def test_debug_internal_policy(self):
        policy = get_policy_for_profile("debug-internal")
        assert policy.allow_partial_meta is True
        assert policy.max_meta_percentage == 100.0
        assert len(policy.enabled_patterns) == 0  # No filtering

    def test_unknown_profile_defaults_to_brand_public(self):
        policy = get_policy_for_profile("unknown")
        brand_public_policy = get_policy_for_profile("brand-public")
        assert policy.allow_partial_meta == brand_public_policy.allow_partial_meta
        assert policy.max_meta_percentage == brand_public_policy.max_meta_percentage


class TestTransformResult:
    """Test TransformResult dataclass."""

    def test_default_values(self):
        result = TransformResult(
            original_text="test",
            transformed_text="test",
        )
        assert result.detections == []
        assert result.changes_made == 0
        assert result.confidence_score == 1.0
        assert result.style_preserved is True
