"""
asset_provenance.py — Track provenance of brand assets through the pipeline.

Records whether each asset was provided by the user, generated by AI, or
composited (AI generation + pixel-exact overlay). Persists to
`.brandmint/asset-provenance.json`.

Distinct from asset_registry.py which handles asset *selection* (which assets
to generate based on domain tags). This module tracks asset *history*.
"""

from __future__ import annotations

import json
import os
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Optional


class AssetSource(str, Enum):
    """How an asset was produced."""

    PROVIDED = "provided"  # User-supplied (logo, product photo)
    GENERATED = "generated"  # AI-generated (Nano Banana Pro, Flux, Recraft)
    COMPOSITED = "composited"  # AI-generated + post-processed with real logo/product overlay
    INPAINTED = "inpainted"  # AI inpainting with real asset in masked region
    EDGE_GUIDED = "edge_guided"  # AI generation guided by logo edge map


@dataclass
class AssetRecord:
    """Provenance record for a single asset."""

    asset_id: str  # e.g., "2A", "3B", "logo-primary"
    source: AssetSource = AssetSource.GENERATED
    file_path: str = ""
    original_path: str = ""  # For provided assets: path to original user file
    model_used: str = ""  # e.g., "nano-banana-pro", "flux-2-pro"
    provider: str = ""  # e.g., "fal", "openrouter"
    seed: Optional[int] = None
    composite_layers: list[str] = field(default_factory=list)  # Paths used in composite
    created_at: str = ""
    metadata: dict = field(default_factory=dict)

    def __post_init__(self):
        if not self.created_at:
            self.created_at = datetime.now(timezone.utc).isoformat()


class AssetProvenance:
    """Track asset provenance, persisted to JSON."""

    DEFAULT_PATH = ".brandmint/asset-provenance.json"

    def __init__(self, base_dir: str):
        self.base_dir = base_dir
        self.store_path = os.path.join(base_dir, self.DEFAULT_PATH)
        self._records: dict[str, AssetRecord] = {}
        self._load()

    def _load(self):
        """Load existing provenance records from disk."""
        if not os.path.exists(self.store_path):
            return
        try:
            with open(self.store_path) as f:
                data = json.load(f)
            for key, rec_data in data.get("assets", {}).items():
                rec_data["source"] = AssetSource(rec_data.get("source", "generated"))
                self._records[key] = AssetRecord(**rec_data)
        except (json.JSONDecodeError, TypeError, KeyError):
            pass  # Start fresh on corrupt data

    def _save(self):
        """Persist all records to disk."""
        os.makedirs(os.path.dirname(self.store_path), exist_ok=True)
        data = {
            "version": 1,
            "updated_at": datetime.now(timezone.utc).isoformat(),
            "assets": {k: asdict(v) for k, v in self._records.items()},
        }
        with open(self.store_path, "w") as f:
            json.dump(data, f, indent=2, default=str)

    def register(self, record: AssetRecord) -> AssetRecord:
        """Register or update an asset provenance record."""
        key = self._make_key(record.asset_id, record.seed)
        self._records[key] = record
        self._save()
        return record

    def register_provided(
        self, asset_id: str, file_path: str, **metadata
    ) -> AssetRecord:
        """Register a user-provided asset (logo, product photo)."""
        record = AssetRecord(
            asset_id=asset_id,
            source=AssetSource.PROVIDED,
            file_path=file_path,
            original_path=file_path,
            metadata=metadata,
        )
        return self.register(record)

    def register_generated(
        self,
        asset_id: str,
        file_path: str,
        model: str = "",
        provider: str = "",
        seed: Optional[int] = None,
        **metadata,
    ) -> AssetRecord:
        """Register an AI-generated asset."""
        record = AssetRecord(
            asset_id=asset_id,
            source=AssetSource.GENERATED,
            file_path=file_path,
            model_used=model,
            provider=provider,
            seed=seed,
            metadata=metadata,
        )
        return self.register(record)

    def register_composited(
        self,
        asset_id: str,
        file_path: str,
        layers: list[str],
        model: str = "",
        provider: str = "",
        seed: Optional[int] = None,
        **metadata,
    ) -> AssetRecord:
        """Register a composited asset (AI + pixel-exact overlay)."""
        record = AssetRecord(
            asset_id=asset_id,
            source=AssetSource.COMPOSITED,
            file_path=file_path,
            model_used=model,
            provider=provider,
            seed=seed,
            composite_layers=layers,
            metadata=metadata,
        )
        return self.register(record)

    def get(self, asset_id: str, seed: Optional[int] = None) -> Optional[AssetRecord]:
        """Get a specific asset record."""
        key = self._make_key(asset_id, seed)
        return self._records.get(key)

    def list_all(self) -> list[AssetRecord]:
        """List all asset records."""
        return list(self._records.values())

    def list_by_source(self, source: AssetSource) -> list[AssetRecord]:
        """List assets filtered by source type."""
        return [r for r in self._records.values() if r.source == source]

    def list_provided(self) -> list[AssetRecord]:
        return self.list_by_source(AssetSource.PROVIDED)

    def list_generated(self) -> list[AssetRecord]:
        return self.list_by_source(AssetSource.GENERATED)

    def list_composited(self) -> list[AssetRecord]:
        return self.list_by_source(AssetSource.COMPOSITED)

    def clear(self):
        """Clear all records."""
        self._records.clear()
        self._save()

    @staticmethod
    def _make_key(asset_id: str, seed: Optional[int] = None) -> str:
        if seed is not None:
            return f"{asset_id}:seed-{seed}"
        return asset_id
