"""
Anti-meta transform pipeline — removes AI/meta content from source prose while
preserving brand voice and style.

NotebookLM generates better artifacts when source documents read as authentic
brand-native prose, not as documents about being generated by AI or about the
generation process.

This module:
1. Detects meta-content patterns (AI references, process descriptions, etc.)
2. Applies transforms to remove or rewrite meta-content
3. Preserves brand voice and style constraints
4. Reports changes for operator review
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple


# ---------------------------------------------------------------------------
# Meta-content pattern definitions
# ---------------------------------------------------------------------------

# Patterns that indicate AI-generated meta-content
AI_META_PATTERNS: List[Tuple[str, re.Pattern]] = [
    ("ai_reference", re.compile(r'\b(?:AI|artificial intelligence|LLM|language model|GPT|Claude|ChatGPT|OpenAI|Anthropic)\b', re.IGNORECASE)),
    ("generation_process", re.compile(r'\b(?:generated|created|produced|synthesized|rendered|built|constructed)\b.*\b(?:by|using|via|with)\b', re.IGNORECASE)),
    ("model_reference", re.compile(r'\b(?:model|algorithm|system|engine)\b.*\b(?:output|result|generation|creation|shows)\b', re.IGNORECASE)),
    ("prompt_reference", re.compile(r'\b(?:prompt|instruction|request|query|input)\b.*\b(?:provided|given|submitted|entered)\b', re.IGNORECASE)),
    ("tool_reference", re.compile(r'\b(?:tool|skill|pipeline|workflow|process|system)\b.*\b(?:used|executed|ran|processed)\b', re.IGNORECASE)),
    ("meta_narrative", re.compile(r'\b(?:this document|this content|this text|this output|this source)\b.*\b(?:was|is|has been)\b.*\b(?:generated|created|produced|written by)\b', re.IGNORECASE)),
    ("disclaimer", re.compile(r'\b(?:note|disclaimer|important|warning|caution)\b[:.]?\s+(?:this|the)\b.*\b(?:AI|generated|automated|synthetic)\b', re.IGNORECASE)),
    ("process_description", re.compile(r'\b(?:first|second|third|next|then|finally|step|phase)\b.*\b(?:we|the system|the pipeline|the tool)\b.*\b(?:generate|create|produce|build)\b', re.IGNORECASE)),
]

# Patterns that are acceptable (brand-native content)
ACCEPTABLE_PATTERNS: List[Tuple[str, re.Pattern]] = [
    ("brand_name", re.compile(r'\b(?:brand|company|product|service)\b.*\b(?:name|identity|voice|tone)\b', re.IGNORECASE)),
    ("marketing_copy", re.compile(r'\b(?:our|we|us)\b.*\b(?:believe|create|deliver|offer|provide)\b', re.IGNORECASE)),
]


@dataclass
class MetaDetection:
    """Result of meta-content detection in a text segment."""
    pattern_name: str
    match_text: str
    start_pos: int
    end_pos: int
    confidence: float  # 0.0-1.0
    suggested_replacement: str = ""


@dataclass
class TransformResult:
    """Result of applying anti-meta transforms to a document."""
    original_text: str
    transformed_text: str
    detections: List[MetaDetection] = field(default_factory=list)
    changes_made: int = 0
    confidence_score: float = 1.0  # Overall confidence in transformation
    style_preserved: bool = True


@dataclass
class AntiMetaPolicy:
    """Policy configuration for anti-meta transforms."""
    # Which pattern categories to detect and remove
    enabled_patterns: Set[str] = field(default_factory=lambda: {
        "ai_reference", "generation_process", "model_reference",
        "prompt_reference", "tool_reference", "meta_narrative",
        "disclaimer", "process_description",
    })
    # Minimum confidence threshold for applying transforms
    min_confidence: float = 0.7
    # Whether to preserve brand voice markers
    preserve_brand_voice: bool = True
    # Whether to allow some meta-content (e.g., for debug-internal profile)
    allow_partial_meta: bool = False
    # Maximum percentage of text that can be meta-content before flagging
    max_meta_percentage: float = 15.0


# ---------------------------------------------------------------------------
# Detection engine
# ---------------------------------------------------------------------------


def detect_meta_content(text: str, policy: Optional[AntiMetaPolicy] = None) -> List[MetaDetection]:
    """Detect meta-content patterns in text."""
    if policy is None:
        policy = AntiMetaPolicy()

    detections = []

    for pattern_name, pattern in AI_META_PATTERNS:
        if pattern_name not in policy.enabled_patterns:
            continue

        for match in pattern.finditer(text):
            # Check if this match overlaps with acceptable patterns
            is_acceptable = False
            for acc_name, acc_pattern in ACCEPTABLE_PATTERNS:
                # Check if the acceptable pattern overlaps with the meta match
                for acc_match in acc_pattern.finditer(text):
                    # If there's significant overlap, consider it acceptable
                    if (acc_match.start() <= match.end() and acc_match.end() >= match.start()):
                        is_acceptable = True
                        break
                if is_acceptable:
                    break

            if is_acceptable:
                continue

            # Calculate confidence based on context
            context_start = max(0, match.start() - 100)
            context_end = min(len(text), match.end() + 100)
            context = text[context_start:context_end]

            confidence = _calculate_confidence(pattern_name, match.group(), context)

            if confidence >= policy.min_confidence:
                detections.append(MetaDetection(
                    pattern_name=pattern_name,
                    match_text=match.group(),
                    start_pos=match.start(),
                    end_pos=match.end(),
                    confidence=confidence,
                    suggested_replacement=_suggest_replacement(pattern_name, match.group(), context),
                ))

    return detections


def _calculate_confidence(pattern_name: str, match_text: str, context: str) -> float:
    """Calculate confidence that a match is truly meta-content."""
    confidence = 0.5  # Base confidence

    # Higher confidence for explicit AI references
    if pattern_name == "ai_reference":
        confidence += 0.3
        if any(word in match_text.lower() for word in ["gpt", "claude", "chatgpt", "openai", "anthropic"]):
            confidence += 0.2

    # Higher confidence for generation process descriptions
    elif pattern_name == "generation_process":
        confidence += 0.2
        if "by ai" in context.lower() or "using ai" in context.lower():
            confidence += 0.3

    # Higher confidence for model references
    elif pattern_name == "model_reference":
        confidence += 0.3
        if "output" in match_text.lower() or "result" in match_text.lower():
            confidence += 0.2

    # Higher confidence for meta-narrative
    elif pattern_name == "meta_narrative":
        confidence += 0.4

    # Higher confidence for disclaimers
    elif pattern_name == "disclaimer":
        confidence += 0.5

    # Context boosts
    if "generated" in context.lower() and "by" in context.lower():
        confidence += 0.1
    if "ai" in context.lower() and "model" in context.lower():
        confidence += 0.1

    return min(1.0, confidence)


def _suggest_replacement(pattern_name: str, match_text: str, context: str) -> str:
    """Suggest a replacement for meta-content."""
    # For now, suggest removal (empty string)
    # Future: could suggest brand-native rewrites
    return ""


# ---------------------------------------------------------------------------
# Transform engine
# ---------------------------------------------------------------------------


def apply_anti_meta_transform(text: str, policy: Optional[AntiMetaPolicy] = None) -> TransformResult:
    """Apply anti-meta transforms to text, returning result with changes."""
    if policy is None:
        policy = AntiMetaPolicy()

    detections = detect_meta_content(text, policy)

    if not detections:
        return TransformResult(
            original_text=text,
            transformed_text=text,
            detections=[],
            changes_made=0,
            confidence_score=1.0,
            style_preserved=True,
        )

    # Sort detections by position (reverse) to avoid offset issues when replacing
    detections.sort(key=lambda d: d.start_pos, reverse=True)

    transformed = text
    changes = 0

    for detection in detections:
        # Apply replacement (empty string means removal)
        replacement = detection.suggested_replacement
        # Always apply replacement if detection confidence meets threshold
        transformed = (
            transformed[:detection.start_pos] +
            replacement +
            transformed[detection.end_pos:]
        )
        changes += 1

    # Clean up any double spaces or awkward spacing from removals
    transformed = re.sub(r'\s{2,}', ' ', transformed)
    transformed = re.sub(r'\n\s*\n\s*\n', '\n\n', transformed)

    # Calculate overall confidence
    meta_chars = sum(d.end_pos - d.start_pos for d in detections)
    meta_percentage = (meta_chars / len(text) * 100) if text else 0
    confidence = 1.0 - (meta_percentage / 100.0)

    # Check if style was preserved (simplified check)
    style_preserved = _check_style_preservation(text, transformed, policy)

    return TransformResult(
        original_text=text,
        transformed_text=transformed,
        detections=detections,
        changes_made=changes,
        confidence_score=confidence,
        style_preserved=style_preserved,
    )


def _check_style_preservation(original: str, transformed: str, policy: AntiMetaPolicy) -> bool:
    """Check if brand voice/style was preserved after transform."""
    if not policy.preserve_brand_voice:
        return True

    # Simple heuristic: check if key brand markers are still present
    # Future: could use more sophisticated style analysis
    brand_markers = ["our", "we", "believe", "create", "deliver"]
    original_markers = sum(1 for m in brand_markers if m.lower() in original.lower())
    transformed_markers = sum(1 for m in brand_markers if m.lower() in transformed.lower())

    # If we lost more than 50% of brand markers, style may not be preserved
    if original_markers > 0:
        return transformed_markers >= (original_markers * 0.5)

    return True


# ---------------------------------------------------------------------------
# Document-level transforms
# ---------------------------------------------------------------------------


def transform_document(doc_text: str, policy: Optional[AntiMetaPolicy] = None) -> TransformResult:
    """Apply anti-meta transforms to an entire document."""
    return apply_anti_meta_transform(doc_text, policy)


def transform_documents(
    documents: Dict[str, str],
    policy: Optional[AntiMetaPolicy] = None
) -> Dict[str, TransformResult]:
    """Apply anti-meta transforms to multiple documents."""
    results = {}
    for doc_id, doc_text in documents.items():
        results[doc_id] = transform_document(doc_text, policy)
    return results


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------


def generate_diff_report(results: Dict[str, TransformResult]) -> str:
    """Generate a human-readable diff report of anti-meta transforms."""
    parts = ["# Anti-Meta Transform Report\n"]

    total_changes = 0
    total_docs = len(results)
    docs_with_changes = 0

    for doc_id, result in sorted(results.items()):
        if result.changes_made == 0:
            continue

        docs_with_changes += 1
        total_changes += result.changes_made

        parts.append(f"## {doc_id}\n")
        parts.append(f"- **Changes:** {result.changes_made}")
        parts.append(f"- **Confidence:** {result.confidence_score:.2f}")
        parts.append(f"- **Style Preserved:** {'Yes' if result.style_preserved else 'No'}")
        parts.append("")

        if result.detections:
            parts.append("### Detections\n")
            for i, detection in enumerate(result.detections, 1):
                parts.append(f"{i}. **{detection.pattern_name}** (confidence: {detection.confidence:.2f})")
                parts.append(f"   - Match: `{detection.match_text[:80]}...`" if len(detection.match_text) > 80 else f"   - Match: `{detection.match_text}`")
                if detection.suggested_replacement:
                    parts.append(f"   - Replacement: `{detection.suggested_replacement}`")
                parts.append("")

    parts.append("\n## Summary\n")
    parts.append(f"- Total documents: {total_docs}")
    parts.append(f"- Documents with changes: {docs_with_changes}")
    parts.append(f"- Total changes: {total_changes}")
    parts.append(f"- Average confidence: {sum(r.confidence_score for r in results.values()) / max(1, len(results)):.2f}")

    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Policy presets
# ---------------------------------------------------------------------------


def get_policy_for_profile(profile_name: str) -> AntiMetaPolicy:
    """Get anti-meta policy preset for a source profile."""
    if profile_name == "brand-public":
        return AntiMetaPolicy(
            enabled_patterns={
                "ai_reference", "generation_process", "model_reference",
                "prompt_reference", "tool_reference", "meta_narrative",
                "disclaimer", "process_description",
            },
            min_confidence=0.7,
            preserve_brand_voice=True,
            allow_partial_meta=False,
            max_meta_percentage=5.0,
        )
    elif profile_name == "strategy-internal":
        return AntiMetaPolicy(
            enabled_patterns={
                "ai_reference", "generation_process", "meta_narrative",
                "disclaimer",
            },
            min_confidence=0.6,
            preserve_brand_voice=True,
            allow_partial_meta=True,
            max_meta_percentage=15.0,
        )
    elif profile_name == "debug-internal":
        return AntiMetaPolicy(
            enabled_patterns=set(),  # No filtering for debug
            min_confidence=0.0,
            preserve_brand_voice=False,
            allow_partial_meta=True,
            max_meta_percentage=100.0,
        )
    else:
        # Default to brand-public policy
        return get_policy_for_profile("brand-public")
