#!/usr/bin/env python3
"""
HeyZack — Illustrations (5A-5C)
Generated by Brandmint pipeline engine.

Provider: fal
"""
import os, sys, subprocess
from dotenv import load_dotenv

load_dotenv(os.path.expanduser("~/.claude/.env"))

BRAND_NAME = "HeyZack"
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(SCRIPT_DIR, "..", "generated")
os.makedirs(OUT_DIR, exist_ok=True)

# Ensure generated scripts can import local brandmint package adapters.
BRANDMINT_REPO_ROOT = "/Volumes/madara/2026/twc-vault/01-Projects/brandmint"
if BRANDMINT_REPO_ROOT and os.path.isdir(BRANDMINT_REPO_ROOT) and BRANDMINT_REPO_ROOT not in sys.path:
    sys.path.insert(0, BRANDMINT_REPO_ROOT)

# Skill reference images directory (composition references for Nano Banana Pro)
SKILL_REF_DIR = os.path.expanduser("~/.claude/skills/brandmint/references/images")

# =============================================================================
# PROVIDER CONFIGURATION
# =============================================================================
# Supports: fal, openrouter, openai, replicate, inference
# All generation goes through core provider adapters.

PROVIDER = os.environ.get("IMAGE_PROVIDER", "fal").lower()
SUPPORTED_PROVIDERS = {"fal", "openrouter", "openai", "replicate", "inference"}
_USE_FALLBACK = PROVIDER == "auto"
if not _USE_FALLBACK and PROVIDER not in SUPPORTED_PROVIDERS:
    print(f"WARNING: Unknown provider '{PROVIDER}', defaulting to FAL.")
    PROVIDER = "fal"

INFERENCE_ENDPOINT = "https://api.inference.sh".strip()
if INFERENCE_ENDPOINT:
    os.environ.setdefault("INFERENCE_BASE_URL", INFERENCE_ENDPOINT)
INFERENCE_APP = "".strip()
if INFERENCE_APP:
    os.environ.setdefault("INFERENCE_IMAGE_APP", INFERENCE_APP)

try:
    from brandmint.core.providers import get_provider as _bm_get_provider
    if _USE_FALLBACK:
        from brandmint.core.providers import generate_with_fallback as _bm_generate_with_fallback
except Exception as e:
    print(f"ERROR: Failed to import core provider adapters: {e}")
    sys.exit(1)

CORE_PROVIDER = None
if not _USE_FALLBACK:
    try:
        CORE_PROVIDER = _bm_get_provider(PROVIDER)
    except Exception as e:
        print(f"ERROR: Provider '{PROVIDER}' is not available: {e}")
        sys.exit(1)

if _USE_FALLBACK:
    print("Using image provider: AUTO (fallback chain)")
else:
    print(f"Using image provider: {PROVIDER.upper()}")

# =============================================================================
# ASSET MODE — composite / inpaint / hybrid post-processing
# =============================================================================
ASSET_MODE = os.environ.get("ASSET_MODE", "generate").lower()
if ASSET_MODE not in ("generate", "composite", "inpaint", "hybrid"):
    print(f"WARNING: Unknown asset mode '{ASSET_MODE}', defaulting to generate.")
    ASSET_MODE = "generate"
if ASSET_MODE != "generate":
    print(f"Asset mode: {ASSET_MODE.upper()}")

NEGATIVE = """cyberpunk neon, sci-fi holograms, floating UI with no device, generic stock family smiles,
generic corporate handshake, all-white sterile showroom, clumsy smart-home cliche,
unrealistic futuristic architecture, glossy toy-like plastic, cartoon, anime, watermark,
text overlay, blurry, low resolution, distorted anatomy, fake app UI, random vendor logos,
  generic smart-home stock rooms, neon cyberpunk holograms, cheesy futuristic HUD overlays, staged handshake business photography, over-posed family smiles"""

# Brand logo file (for visual reference injection — empty if no logo configured)
LOGO_PATH = "/Volumes/madara/2026/twc-vault/01-Projects/brandmint/brandmint-run/heyzack-ai/logo-wordmark.png"

def upload_reference(path):
    """Resolve a local reference path; provider adapters handle upload semantics."""
    if not path or not os.path.exists(path):
        return None
    return os.path.abspath(path)

_logo_url_cache = None
def get_logo_url():
    """Upload brand logo once and cache the URL for reuse."""
    global _logo_url_cache
    if _logo_url_cache:
        return _logo_url_cache
    if LOGO_PATH and os.path.exists(LOGO_PATH):
        print(f"  Uploading brand logo: {os.path.basename(LOGO_PATH)}")
        _logo_url_cache = upload_reference(LOGO_PATH)
        return _logo_url_cache
    return None


# Product reference images (actual product photos for Nano Banana Pro accuracy)
PRODUCT_REF_PATHS = []

_product_ref_url_cache = None
def get_product_ref_urls():
    """Upload product reference images once and cache URLs for reuse."""
    global _product_ref_url_cache
    if _product_ref_url_cache is not None:
        return _product_ref_url_cache
    _product_ref_url_cache = []
    for p in PRODUCT_REF_PATHS:
        if os.path.exists(p):
            print(f"  Uploading product ref: {os.path.basename(p)}")
            uploaded = upload_reference(p)
            if uploaded:
                _product_ref_url_cache.append(uploaded)
    return _product_ref_url_cache


# Reference image mapping: prompt ID -> composition reference filename
REF_IMAGES = {
    "2A": "ref-2A-bento-grid.jpg",
    "2B": "ref-2B-brand-seal.jpg",
    "2C": "ref-2C-logo-emboss.jpg",
    "3A": "ref-3A-capsule-collection.jpg",
    "3B": "ref-3B-hero-product.jpg",
    "3C": "ref-3C-essence-vial.jpg",
    "4A": "ref-4A-catalog-layout.jpg",
    "4B": "ref-4B-flatlay.jpg",
    "5A": "ref-5A-heritage-engraving.jpg",
    "5B": "ref-5B-campaign-grid.jpg",
    "5D": "ref-5D-engine-icons.jpg",
    "7A": "ref-7A-contact-sheet.jpg",
    "8A": "ref-8A-seeker-poster.jpg",
    "9A": "ref-9A-engine-poster.jpg",
    "10A": "ref-7A-contact-sheet.jpg",
    "10B": "ref-7A-contact-sheet.jpg",
    "10C": "ref-7A-contact-sheet.jpg",
}

# Config-driven reference image overrides
REF_OVERRIDES = {
    "3A": "ref-alt-leather-duffles.jpg",
}
REF_IMAGES.update(REF_OVERRIDES)


def get_ref_image(pid):
    """Get composition reference image path for a prompt ID."""
    fname = REF_IMAGES.get(pid, "")
    if fname:
        path = os.path.join(SKILL_REF_DIR, fname)
        if os.path.exists(path):
            return path
    return None


# Supplementary composition references (dynamically selected from full catalog)
SUPP_REFS = {
    "2A": ['ref-style-bold-portrait-grid.jpg', 'ref-tw-200-AmirMushich-nano-banana-smart-prompt.jpg', 'ref-tw-198-d4m1n-bonus-elysia-premium-fashion.jpg'],
    "3A": ['ref-alt-passport-covers.jpg', 'ref-alt-product-branding-workflow.jpg', 'ref-alt-branded-shoes.jpg'],
    "3B": ['ref-alt-passport-covers.jpg', 'ref-tw-220-AmirMushich-be-typography-designer-drive.jpg', 'ref-alt-branded-shoes.jpg'],
    "3C": ['ref-alt-passport-covers.jpg', 'ref-alt-branded-shoes.jpg', 'ref-alt-sneaker-collabs.jpg'],
    "4A": ['ref-alt-dieline-to-3d.jpg', 'ref-alt-product-branding-workflow.jpg', 'ref-alt-passport-covers.jpg'],
    "4B": ['ref-alt-boxing-gloves.jpg', 'ref-alt-passport-covers.jpg', 'ref-alt-branded-shoes.jpg'],
    "5B": ['ref-style-collage-portraits.jpg', 'ref-tw-119-AmirMushich-nano-banana-smart-prompt.jpg', 'ref-tw-122-oggii_0-gemini-nano-banana-pro-prompt.jpg'],
    "7A": ['ref-style-bold-portrait-grid.jpg', 'ref-tw-200-AmirMushich-nano-banana-smart-prompt.jpg', 'ref-tw-198-d4m1n-bonus-elysia-premium-fashion.jpg'],
    "8A": ['ref-style-bold-portrait-grid.jpg', 'ref-tw-201-AmirMushich-nano-banana-smart-prompt-font.jpg', 'ref-tw-200-AmirMushich-nano-banana-smart-prompt.jpg'],
    "9A": ['ref-alt-3d-sticker-logos.jpg', 'ref-tw-201-AmirMushich-nano-banana-smart-prompt-font.jpg', 'ref-tw-200-AmirMushich-nano-banana-smart-prompt.jpg'],
}

_supp_ref_url_cache = {}
def get_supp_ref_images(pid, limit=3):
    """Get supplementary composition reference URLs for a prompt ID.

    Uploads images on first call, caches for reuse.
    Returns list of uploaded URLs (may be empty).
    """
    if pid in _supp_ref_url_cache:
        return _supp_ref_url_cache[pid]
    urls = []
    for fname in SUPP_REFS.get(pid, [])[:limit]:
        path = os.path.join(SKILL_REF_DIR, fname)
        if os.path.exists(path):
            print(f"  Uploading supp ref: {os.path.basename(path)}")
            uploaded = upload_reference(path)
            if uploaded:
                urls.append(uploaded)
    _supp_ref_url_cache[pid] = urls
    return urls


def _normalize_png_if_needed(filepath):
    """Convert JPEG/WebP/SVG payloads into PNG when output path expects PNG."""
    if not filepath.endswith(".png") or not os.path.exists(filepath):
        return
    with open(filepath, "rb") as f:
        header = f.read(64)
    if header.startswith(b"\x89PNG"):
        return

    try:
        if header[:2] == b"\xff\xd8" or header[:4] == b"RIFF":
            subprocess.run(
                ["sips", "-s", "format", "png", filepath, "--out", filepath],
                check=True,
                capture_output=True,
            )
            return

        head_text = header.decode("utf-8", errors="ignore").lstrip().lower()
        if head_text.startswith("<?xml") or "<svg" in head_text:
            tmp_svg = filepath + ".svg.tmp"
            os.replace(filepath, tmp_svg)
            try:
                subprocess.run(
                    ["rsvg-convert", "-w", "2048", "-h", "2048", "--keep-aspect-ratio", tmp_svg, "-o", filepath],
                    check=True,
                    capture_output=True,
                )
            finally:
                if os.path.exists(tmp_svg):
                    os.remove(tmp_svg)
            return
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        print(f"  WARNING: failed to normalize image payload at {filepath}: {e}")


def _composite_post_pass(output_path, pid=""):
    """Apply composite post-processing if ASSET_MODE != generate.

    Overlays real brand logo onto AI-generated images using the compositor engine.
    Saves the composited result as {name}-composited.png alongside the original.
    """
    if ASSET_MODE == "generate":
        return
    if not os.path.exists(output_path):
        return

    try:
        from brandmint.core.asset_mode import AssetMode, route_asset
        from brandmint.core.compositor import PostGenCompositor

        mode = AssetMode(ASSET_MODE)
        decision = route_asset(
            asset_id=pid or os.path.basename(output_path),
            global_mode=mode,
            has_logo=bool(LOGO_PATH and os.path.exists(LOGO_PATH)),
            has_product_images=bool(PRODUCT_REF_PATHS),
        )

        if not decision.needs_composite_pass:
            return
        if not LOGO_PATH or not os.path.exists(LOGO_PATH):
            print(f"  SKIP composite: no logo file at {LOGO_PATH}")
            return

        # Build composited output path (preserve original)
        base, ext = os.path.splitext(output_path)
        composited_path = f"{base}-composited{ext}"

        compositor = PostGenCompositor()
        compositor.composite_pass_with_analysis(
            generated_image_path=output_path,
            logo_path=LOGO_PATH,
            output_path=composited_path,
        )

        if os.path.exists(composited_path):
            size_kb = os.path.getsize(composited_path) / 1024
            print(f"  Composited: {os.path.basename(composited_path)} ({size_kb:.0f} KB)")
    except ImportError as e:
        print(f"  WARNING: composite pass unavailable (missing dependency): {e}")
    except Exception as e:
        print(f"  WARNING: composite post-pass failed: {e}")


def gen_with_provider(
    prompt,
    model,
    output_path,
    width=1024,
    height=1024,
    image_url=None,
    image_urls=None,
    negative_prompt="",
    **kwargs,
):
    """Generate with core provider adapters (single or auto-fallback)."""
    primary_ref = image_url
    if primary_ref is None and isinstance(image_urls, list) and image_urls:
        primary_ref = image_urls[0]

    if _USE_FALLBACK:
        result = _bm_generate_with_fallback(
            prompt=prompt,
            model=model,
            output_path=output_path,
            width=width,
            height=height,
            image_url=primary_ref,
            negative_prompt=negative_prompt,
            image_urls=image_urls,
            **kwargs,
        )
    else:
        if CORE_PROVIDER is None:
            return False
        result = CORE_PROVIDER.generate(
            prompt=prompt,
            model=model,
            output_path=output_path,
            width=width,
            height=height,
            image_url=primary_ref,
            negative_prompt=negative_prompt,
            image_urls=image_urls,
            **kwargs,
        )

    if not (result and result.success):
        err = result.error if result else "unknown adapter error"
        provider_label = "AUTO" if _USE_FALLBACK else PROVIDER
        print(f"  ERROR: generation failed for {model} via {provider_label}: {err}")
        return False

    _normalize_png_if_needed(output_path)
    if os.path.exists(output_path):
        size_kb = os.path.getsize(output_path) / 1024
        print(f"  Saved: {os.path.basename(output_path)} ({size_kb:.0f} KB)")

    # Composite post-pass: overlay real logo/product if ASSET_MODE != generate
    _composite_post_pass(output_path)

    return True


def gen_recraft(pid, slug, prompt, style, colors, size, seeds=(42, 137)):
    """Generate with Recraft V3 via unified core provider adapter path."""
    size_dims = {"square": (1024, 1024), "landscape_16_9": (1792, 1024), 
                 "portrait_9_16": (1024, 1792), "1024x1024": (1024, 1024)}
    w, h = size_dims.get(size, (1024, 1024))
    
    for seed in seeds:
        variant = "v1" if seed == 42 else f"v{seed}"
        out_path = os.path.join(OUT_DIR, f"{pid}-{slug}-recraft-{variant}.png")
        print(f"\n  [{pid}] Recraft V3 ({style}) seed={seed} (provider: {PROVIDER})...")
        enhanced_prompt = f"{prompt}. Style: {style}. Fine line art, detailed illustration."
        gen_with_provider(
            enhanced_prompt,
            "recraft-v3",
            out_path,
            w,
            h,
            negative_prompt="",
            seed=seed,
            image_size=size,
            style=style,
            colors=colors,
        )


def gen_nano_banana(pid, slug, prompt, aspect, image_urls, seeds=(42, 137)):
    """Generate with Nano Banana Pro via unified core provider adapter path."""
    full_prompt = f"{prompt}\n\nAvoid: {NEGATIVE}"
    
    # Parse aspect ratio to get dimensions
    aspect_dims = {"16:9": (1792, 1024), "9:16": (1024, 1792), "1:1": (1024, 1024), 
                   "3:4": (896, 1152), "4:3": (1152, 896)}
    w, h = aspect_dims.get(aspect, (1024, 1024))
    
    for seed in seeds:
        variant = "v1" if seed == 42 else f"v{seed}"
        out_path = os.path.join(OUT_DIR, f"{pid}-{slug}-nanobananapro-{variant}.png")
        print(f"\n  [{pid}] Nano Banana Pro seed={seed} (provider: {PROVIDER})...")
        gen_with_provider(
            full_prompt,
            "nano-banana-pro",
            out_path,
            w,
            h,
            image_urls=image_urls,
            negative_prompt="",
            seed=seed,
            aspect_ratio=aspect,
            resolution="2K",
            output_format="png",
            num_images=1,
        )


PROMPT_5A = """HeyZack clean technical line illustration logomark. Clean technical illustration with rounded iconography, subtle architectural linework, and blue-to-pink energy flow accents..
Technical circuit-board filigree style — sigil rendered as PCB trace diagram, organic botanical forms replaced by precise node-and-trace geometry. Thin delicate hairlines in organic curves. Airy, precise, no heavy borders.
Central sigil: A stylized pink Z mark with rounded contours and forward-leaning motion. forward-leaning Z silhouette, rounded ribbon geometry, pink energy core. Digital precision engraving — hairline circuit traces, component nodes at structural points, Savings Green (#22C55E) accent on active nodes. Rendered as
botanical-scientific diagram. "HeyZack" in geometric serif (SF Pro Display
style), wide spacing. Below: "EST. MMXXVI" lighter weight. Light Grey
(#E9EDEF) paper. HeyZack Blue (#243984) lines. HeyZack Pink
(#E82F89) accent on borders. Digital-organic synthesis, bio-circuit aes"""

PROMPT_5B = """HeyZack Campaign Visual Identity Grid. 2-column
asymmetrical layout. Full bleed, zero spacing between tiles.
Core metaphor: An invisible conductor synchronizing climate, access, lighting, security, and energy across every room and property.. Visual territory: consumer-simple, operator-grade building automation with real AI learning, visible savings, and no vendor lock-in.
TYPE A: Solid HeyZack Blue (#243984) background with pattern at 5% opacity,
centered sigil in Light Grey (#E9EDEF).
TYPE B: HeyZack Pink (#E82F89) background, "AI Automation for Residential & Commercial Buildings" in SF Pro Display
Semibold, Light Grey text.
TYPE C: High-contrast duotone photographs using #243984 + #E82F89.
Materials: brushed aluminum, tempered glass, matte polycarbonate, smoked acrylic, satin black steel, powder-coated white metal, soft-touch silicone, edge-lit LED acrylic, stainless fasteners, architectural plaster, natural oak, dark stone countertops. No stock-photo cliches. No sterile all-white showrooms. No sci-fi holograms. Prefer real hands, candid use, and product-in-context framing.. Typography: SF Pro Display ONLY.
HeyZack Blue 60% backgrounds. Light Grey 30% text/surfaces. HeyZack Pink 10% highlights ONLY. Every photo unique. Clean technical illustration with rounded iconography, subtle architectural linework, and blue-to-pink energy flow accents..
 Extreme attention to micro-detail: material grain, light caustics, sub-surface scattering, fiber textures."""

PROMPT_5C = """HeyZack conceptual panel illustration. Clean technical illustration with rounded iconography, subtle architectural linework, and blue-to-pink energy flow accents..
Bold geometric abstraction — theme rendered through pure geometric shapes only, no figurative elements, flat color planes create spatial depth through overlap. Apple keynote graphics, premium proptech pitch systems, smart-home dashboard illustration, and modern outlined icon families. Core metaphor: An invisible conductor synchronizing climate, access, lighting, security, and energy across every room and property.. Mood: intelligent, trustworthy, modern, connected, efficient, premium, human-centered, responsive, architectural, retrofit-friendly.
High contrast geometric color blocks: #243984 dominant planes, #E82F89 accent shapes, #E9EDEF negative space lines between forms. Flowing organic lines, flat color planes in HeyZack Blue
(#243984), HeyZack Pink (#E82F89), and Savings Green (#22C55E).
HeyZack Blue 60% backgr"""

STYLE_ANCHOR = os.path.join(OUT_DIR, "2A-brand-kit-bento-nanobananapro-v1.png")


def main():
    print("=" * 60)
    print(f"{BRAND_NAME} -- Illustrations (5A-5C)")
    print("=" * 60)

    # Verify Recraft prompt lengths
    for pid, p in {"5A": PROMPT_5A, "5C": PROMPT_5C}.items():
        count = len(p)
        status = "OK" if count < 1000 else "OVER LIMIT"
        print(f"  {pid}: {count} chars [{status}]")
        if count >= 1000:
            print("ERROR: Prompt exceeds 1000 char Recraft V3 limit. Condense it.")
            sys.exit(1)

    # 5A: Heritage Engraving (Recraft digital_illustration)
    print("\n--- 5A: Heritage Engraving (Recraft V3 digital) ---")
    gen_recraft("5A", "heritage-engraving", PROMPT_5A,
                "digital_illustration",
                ["#243984", "#E9EDEF", "#E82F89"],
                "square_hd")

    # 5B: Campaign Grid (Nano Banana Pro + anchor + comp ref)
    print("\n--- 5B: Campaign Grid (Nano Banana Pro) ---")
    anchor_urls = []
    if os.path.exists(STYLE_ANCHOR):
        anchor_url = upload_reference(STYLE_ANCHOR)
        if anchor_url:
            anchor_urls = [anchor_url]
    logo_url = get_logo_url()
    if logo_url:
        anchor_urls.append(logo_url)
    ref_5b = get_ref_image("5B")
    if ref_5b:
        print(f"  Adding composition ref: {os.path.basename(ref_5b)}")
        ref_url = upload_reference(ref_5b)
        if ref_url:
            anchor_urls.append(ref_url)
    anchor_urls.extend(get_supp_ref_images("5B"))
    gen_nano_banana("5B", "campaign-grid", PROMPT_5B, "3:4", anchor_urls)

    # 5C: Art Panel (Recraft digital_illustration)
    print("\n--- 5C: Art Panel (Recraft V3 digital) ---")
    gen_recraft("5C", "art-panel", PROMPT_5C,
                "digital_illustration",
                ["#243984", "#E82F89", "#22C55E"],
                "portrait_4_3")

    print("\n" + "=" * 60)
    print("  ILLUSTRATIONS COMPLETE (5A-5C)")
    print("=" * 60)


if __name__ == "__main__":
    main()
